# Generated by Django 5.1.6 on 2025-02-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='updated_at',
        ),
    ]
